print('Git Project-1 feature-1 add')
print('Git Project-2 Feature-2 add')
print('Git Project-2 Feature-3 add')
print('Git Project-2 Feature-4 add')
print('Git Project-2 Feature-update-1 add')
print('Git Project-2 new-dummy-1 add')
print('Git Project-2 new-dummy-2 add')
print('Git Project-2 new-dummy-3 add')
print('Git Project-4 New-stash-feature-1 add')
print('Git Project-4 New-stash-feature-2 add')
print('Git Project-4 New-revert-feature-3 add')
print('revert-feature-1 add')